### ISSUE TITLE
Change expression AST to simplify impl blocks

### ISSUE THREAD

**Issue by kontheocharis** [hash-org/hashc#629]
Currently, the AST structure is weird when it comes to impl blocks:
- There is `ImplDef`, which is an anonymous impl with type parameters but no subject
- There is `TraitImpl`, which is a trait impl block with no parameters but a (trait?) subject

Instead, there should probably be only an `ImplDef`, which has a subject and parameters `impl <T, ..> S {...}`, and can be used to implement methods on data types (since we aren't dealing with traits yet). In the future it can be extended with two subjects (`impl <T,..> A for B {...}`) when traits are supported.

thoughts @feds01  ?

**Comment by kontheocharis** [comment]
I think the latter would be better, though we should hold off on the `for` syntax until traits are functional ?

**Comment by feds01** [comment]
Yeah, I agree with this change. It would be nice if we wrote a formal specification/grammar for this, so we don't forget later on when we come to implementing this.
