### ISSUE TITLE
Update book documentation to match latest language spec

### ISSUE THREAD

**Issue by kontheocharis** [hash-org/hashc#631]
The current book documentation has gotten out of sync with the current implementation, mostly relating to syntax changes:
- We don't have semi colons anymore
- Impl syntax is different
- Generic parameters have different syntax; they are no longer type functions
- Type functions are just a special case of implicit functions
- Pure and unsafe keywords in front of functions

**Comment by feds01** [comment]
See [hash-org.github.io/spec/](https://hash-org.github.io/spec/)
