### ISSUE TITLE
ui: add command-line help menu

### ISSUE THREAD

**Issue by feds01** [hash-org/hashc#785]
Since we removed clap, the command line doesn't have a help menu anymore. This should be re-added and all options should be documented via the book and in the help menu.

**Comment by kontheocharis** [comment]
We decided that we are going to re-work the compiler arguments "hashc" into a selection of key-value pairs instead of different modes and `-C<key>=<value>` style of options; everything after this work should have the shape of `--<opt-key>=<value>`.
