### ISSUE TITLE
Add attributes to expressions and modules

### ISSUE THREAD

**Issue by feds01** [hash-org/hashc#896]
# Initial thoughts and specification
Attributes are an "extension" of directives to allow various configurations to be applied to items/modules. The proposed syntax is to add a new `Expr::Attribute { inner: Expr, attrs: Attributes }` expression variant. `Attributes` is then defined as a 
either a `Vec<Attribute>` or `HashMap<Identifier, Attribute>`.

The general proposed syntax for attributes is:
- For items: `#[attr1, attr2, ...]`
- For modules `#![attr1, attr2, ...]`

This borrows the syntax from Rust, but I think it is well-suited. Other suggestions are welcome.

As for the attribute itself, there should be a few variants:
- `Name` attribute, simply some identifier or path which specifies that the attribute exists, e.g. `no_mangle`, `foreign`, etc.
- `Key` attribute, an attribute with an associated name and a value, such as an identifier or literal e.g. `tag=4` specifying that the compiler should use 4bytes for an enum tag.
- `Call` attribute, an attribute that has an associated name, and then a collection of values that are associated with the name: `x(a, b, c)`.

This means that `Attribute` becomes an `enum`:
```rs
enum Attribute {
    Name(Identifier),  // ident
    Value(Identifier, AttributeValue), // ident = value
    Call(Attributes) // ident(attr1, attr2, attr3, ...) maybe call this "group" instead.
}
```

Furthermore, since attributes are queried by most parts of the compiler, from untyped-semantics to codegen, I propose that such attributes are added to a static store of their own which can be accessed by an `AttrId`. The attributes should be constructed and added to the static attributes store at some stage, potentially during the `ast-expand` pass. Then, those parts of the compiler which need to query attributes can then use `AttrId` and query attributes. 

However, there are still some un-answered questions:
- ~~How to make it so that each part of the code knows which TIR/AST node has which `AttrId`?~~
- ~~Ensure that we're not over-storing attributes, since most things won't have any attributes on them.~~
- ~~Does the syntax make sense, and should attributes be allowed everywhere an expression is allowed?~~

# Action List

- [x] #922
- [x] #916
- [ ] #915 
- [x] #924
- [x] #925
- [x] #926
   - [ ] Attribute values can only be literals for now. Implement a check that ensures this is the case. This should happen at `hash-expand`.
   - [ ] Ensure the subjects that an attribute is applied to is valid.
   - [ ] Ensure non-existent macros/attributes emit an error.
   - [ ] `hash-expand` pass must be invoked straight after parsing.
- [ ] #927

**Comment by kontheocharis** [comment]
How will checking work for these attributes? Is there a way this can just be a compile time function rather than another special construct?

**Comment by kontheocharis** [comment]
I also think this should be the same as "directives", they shouldn't be two different things.

**Comment by kontheocharis** [comment]
like maybe `#foo` desugars to `#[foo]`

**Comment by feds01** [comment]
Well, the kind of checking that needs to occur for the attributes depends on certain compiler information that would need to be available. It is too early to think about making this a compile-time function, and the compiler itself cares about some of these labels, e.g. if some item name should not be mangled `no_mangle`.

**Comment by feds01** [comment]
> like maybe `#foo` desugars to `#[foo]`

I agree that attributes and directives shouldn't be different.

**Comment by kontheocharis** [comment]
So basically this is just registering a bunch of untyped data on items? And then later on down the line stages will pick this up and deal accordingly?

**Comment by kontheocharis** [comment]
Two things:
1) Ideally we still want to check this somehow. I.e. if someone writes `#[no_mangl]` there should be something that says "attribute no_mangl not found, did you mean no_mangle?". Additionally `#[repr()]` should say "attribute `repr` expects one argument" or something like that

**Comment by feds01** [comment]
> Two things:
> 
> 1. Ideally we still want to check this somehow. I.e. if someone writes `#[no_mangl]` there should be something that says "attribute no_mangl not found, did you mean no_mangle?". Additionally `#[repr()]` should say "attribute `repr` expects one argument" or something like that
> 2. It would be nice eventually to be able to run compile-time functions on items using a similar syntax, idk if this should be the same thing or something different.

Yeah, that's right, we need a way to register attributes, and to register what kind of arguments and data they accept programmatically so we can check them at some point (maybe even in untyped-semantics).

**Comment by kontheocharis** [comment]
But then where do you stop? Are valid arguments just identifiers? Or nested calls? Strings/integers/maps/lists etc?

**Comment by kontheocharis** [comment]
Which parts of the compiler utilise attributes which are before tc?

**Comment by kontheocharis** [comment]
Also Rust takes the approach of integrating these with proc macros, is that something we want to do?

**Comment by feds01** [comment]
Pre-TC uses:
- `untyped-semantics` only "checks" that they are valid.
-  `expand` checks for `dump_ast` and consequently dumps the AST.
There are the ones I can think of atm.

**Comment by feds01** [comment]
> Also Rust takes the approach of integrating these with proc macros, is that something we want to do?

The Rust approach to proc-macros is somewhat obsolete if we eventually add compile-time functions which can add code.

**Comment by kontheocharis** [comment]
We require more or less three different kinds of attributes:
1. AST-level attributes like `#dump-ast` which operate on the AST of the item
2. Attributes like `#memoise` which act as compile-time functions that take in a function and return a new function
3. Code-generation related attributes which customise the emitted code, like `#repr` or `#no_mangle`

There are also a bunch of other kinds of attributes such as `#derive` for which it is not clear which layer they will operate on. For example, you can imagine `#derive` being a macro, or it being a compile-time function that does some reflection to see the fields of the type it is given.

**Comment by kontheocharis** [comment]
So my questions:
1) Should each of these be a completely different construct, or should they all be under one umbrella somehow?
2) How do we deal with checking on a general basis, while still remaining declarative and not hardcoding all the directives like now?
3) How do we allow user-defined attributes at each of these levels?

**Comment by feds01** [comment]
The first steps I think are to:
- Allow for a general syntax as the one to be proposed above to be parsed and registered into for now what we will call "attributes". The syntax captures all of the things that we might want to do in the future with such attributes.
- Move out dealing with attributes from TC, as in you probably shouldn't need to depend on `Env` to read what attributes are on what (although this might be difficult if not impossible)?
- Set up some kind of macro/proc-macro to declaratively define what attributes we currently allow, what to allow and what to allow them on i.e. `struct`, `enum`, `function`. 

User-defined attributes:
- We might have to add a special attribute that can register functions as an attribute, although I am not sure about what limitations these will have, and how to make it so that they run at a particular time. Will these need some kind of compiler API?

**Comment by kontheocharis** [comment]
Maybe the compiler API can provide something like

```rs
compiler.register_attribute("memoise", AttributeLayer::Cte, on=AttributeTarget::Fn, (item: ((...U) -> T)) => ...)
compiler.register_attribute("dump_ast_custom", AttributeLayer::Ast, on=AttributeTarget::Any, (item: AstItem) => ...)
compiler.register_attribute("refcount", AttributeLayer::Codegen, on=AttributeTarget::Var, (item: LowLevelItem) => ...)
```
