### ISSUE TITLE
ir+lower: consider localising `Projections` to each body

### ISSUE THREAD

**Issue by feds01** [hash-org/hashc#996]
## Description

Currently, projections are interned in the global IR projection store. However, there is no need for the items to be all in a global store since the projections have no relation to one another beyond the scope of a `Body`. A potential change could be introduced to make all local projections be stored on the `Body`.

## Why do this?

In the future, we want to parallelise IR building and optimising as much as possible. The thing that hurts the most is the contention on locking (even if we are just reading it, there is still overhead). In order to completely avoid locking when reading projections, we could just store them local to a body, and read them with the owning `Body` in scope.

## Required changes
- Change the IR to store local projections on the `Body`
- Change lowering to use and create projections on the built body. 
- Change the IR visitors to access projections from the owning `Body`

**Comment by kontheocharis** [comment]
This is a good idea to do as much as possible, in all places that utilise concurrent stores
